
nginx:
  image: nginx:stable
  volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    - ./src:/var/www/html
  links:
    - php:php
  ports:
    - 80:80

php:
  image: tombusby/php-fpm-mysql:latest
  volumes:
    - ./php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:ro
    - ./src:/var/www/html
  links:
    - mysql:mysql
  expose:
    - 9000

# This will terminate once the migrations have been run
run-migrations:
  image: tombusby/php-fpm-mysql:latest
  command: sh -c 'until php artisan migrate; do sleep 1; done'
  links:
    - mysql:mysql
  volumes:
    - ./src:/var/www/html

mysql:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: 7wZTJyKbxfBt51o2fe2k  
    MYSQL_DATABASE: laravel
    MYSQL_USER: lavarel
    MYSQL_PASSWORD: hunter2

